-- AlterTable
ALTER TABLE `User` ADD COLUMN `avatarType` ENUM('SOLID', 'GRADIENT', 'GLASS', 'IMAGE') NULL;
ALTER TABLE `User` ADD COLUMN `avatarValue` VARCHAR(2048) NULL;
ALTER TABLE `User` ADD COLUMN `bannerType` ENUM('SOLID', 'GRADIENT', 'GLASS', 'IMAGE') NOT NULL DEFAULT 'GRADIENT';
ALTER TABLE `User` ADD COLUMN `bannerValue` VARCHAR(2048) NOT NULL DEFAULT '#C6B3FF|#6427C8';
