export interface EmojiItem {
  emoji: string;
  keywords: readonly string[];
}

export const EMOJI_LIBRARY: EmojiItem[] = [
  { emoji: "😀", keywords: ["웃", "기쁨", "스마일"] },
  { emoji: "😄", keywords: ["웃", "행복"] },
  { emoji: "😍", keywords: ["하트", "좋아"] },
  { emoji: "😎", keywords: ["쿨", "선글라스"] },
  { emoji: "🤔", keywords: ["생각", "고민"] },
  { emoji: "😴", keywords: ["잠", "피곤"] },
  { emoji: "😭", keywords: ["울음", "슬픔"] },
  { emoji: "😡", keywords: ["화남", "짜증"] },
  { emoji: "💀", keywords: ["해골"] },
  { emoji: "👻", keywords: ["유령"] },
  { emoji: "👽", keywords: ["외계인"] },
  { emoji: "🤖", keywords: ["로봇", "ai"] },
  { emoji: "💩", keywords: ["똥"] },
  { emoji: "👋", keywords: ["안녕", "손"] },
  { emoji: "👍", keywords: ["좋아요", "엄지"] },
  { emoji: "👎", keywords: ["싫어요"] },
  { emoji: "👏", keywords: ["박수"] },
  { emoji: "🙏", keywords: ["부탁", "감사", "기도"] },
  { emoji: "💪", keywords: ["힘", "운동"] },
  { emoji: "👀", keywords: ["눈", "보기"] },
  { emoji: "🧠", keywords: ["뇌", "아이디어", "생각"] },
  { emoji: "🧑‍💻", keywords: ["개발", "코딩", "프로그래머"] },
  { emoji: "👩‍🎨", keywords: ["디자이너", "그림"] },
  { emoji: "👨‍🍳", keywords: ["요리", "셰프"] },
  { emoji: "🧑‍🚀", keywords: ["우주", "로켓"] },
  { emoji: "👶", keywords: ["아기"] },
  { emoji: "🐶", keywords: ["강아지", "개", "동물"] },
  { emoji: "🐱", keywords: ["고양이", "냥"] },
  { emoji: "🐭", keywords: ["쥐"] },
  { emoji: "🐹", keywords: ["햄스터"] },
  { emoji: "🐰", keywords: ["토끼"] },
  { emoji: "🦊", keywords: ["여우"] },
  { emoji: "🐻", keywords: ["곰"] },
  { emoji: "🐼", keywords: ["판다"] },
  { emoji: "🐨", keywords: ["코알라"] },
  { emoji: "🐯", keywords: ["호랑이"] },
  { emoji: "🦁", keywords: ["사자"] },
  { emoji: "🐮", keywords: ["소"] },
  { emoji: "🐷", keywords: ["돼지"] },
  { emoji: "🐸", keywords: ["개구리"] },
  { emoji: "🐵", keywords: ["원숭이"] },
  { emoji: "🐔", keywords: ["닭"] },
  { emoji: "🐧", keywords: ["펭귄"] },
  { emoji: "🐦", keywords: ["새"] },
  { emoji: "🐤", keywords: ["병아리"] },
  { emoji: "🦆", keywords: ["오리"] },
  { emoji: "🦉", keywords: ["owl", "부엉이"] },
  { emoji: "🐝", keywords: ["벌"] },
  { emoji: "🦋", keywords: ["나비"] },
  { emoji: "🐢", keywords: ["거북"] },
  { emoji: "🐙", keywords: ["문어"] },
  { emoji: "🐠", keywords: ["물고기"] },
  { emoji: "🐳", keywords: ["고래"] },
  { emoji: "🐬", keywords: ["돌고래"] },
  { emoji: "🌸", keywords: ["꽃", "벚꽃"] },
  { emoji: "🌹", keywords: ["장미"] },
  { emoji: "🌻", keywords: ["해바라기"] },
  { emoji: "🌷", keywords: ["튤립"] },
  { emoji: "🌱", keywords: ["새싹", "식물"] },
  { emoji: "🌲", keywords: ["나무", "숲"] },
  { emoji: "🍀", keywords: ["클로버", "행운"] },
  { emoji: "🍁", keywords: ["단풍"] },
  { emoji: "🍄", keywords: ["버섯"] },
  { emoji: "🍇", keywords: ["포도"] },
  { emoji: "🍉", keywords: ["수박"] },
  { emoji: "🍊", keywords: ["오렌지", "귤"] },
  { emoji: "🍋", keywords: ["레몬"] },
  { emoji: "🍌", keywords: ["바나나"] },
  { emoji: "🍎", keywords: ["사과"] },
  { emoji: "🍓", keywords: ["딸기"] },
  { emoji: "🍑", keywords: ["복숭아"] },
  { emoji: "🍍", keywords: ["파인애플"] },
  { emoji: "🥑", keywords: ["아보카도"] },
  { emoji: "🌶️", keywords: ["매운", "고추"] },
  { emoji: "🍞", keywords: ["빵"] },
  { emoji: "🧀", keywords: ["치즈"] },
  { emoji: "🍔", keywords: ["햄버거"] },
  { emoji: "🍕", keywords: ["피자"] },
  { emoji: "🍟", keywords: ["감자", "감자튀김"] },
  { emoji: "🌭", keywords: ["핫도그"] },
  { emoji: "🥪", keywords: ["샌드위치"] },
  { emoji: "🌮", keywords: ["타코"] },
  { emoji: "🍣", keywords: ["초밥", "스시"] },
  { emoji: "🍜", keywords: ["라면", "국수"] },
  { emoji: "🍱", keywords: ["도시락"] },
  { emoji: "🍚", keywords: ["밥"] },
  { emoji: "🍦", keywords: ["아이스크림"] },
  { emoji: "🍩", keywords: ["도넛"] },
  { emoji: "🍪", keywords: ["쿠키"] },
  { emoji: "🎂", keywords: ["케이크", "생일"] },
  { emoji: "🍫", keywords: ["초콜릿"] },
  { emoji: "🍿", keywords: ["팝콘", "영화"] },
  { emoji: "☕", keywords: ["커피", "카페"] },
  { emoji: "🍵", keywords: ["차", "녹차"] },
  { emoji: "🍺", keywords: ["맥주", "술"] },
  { emoji: "🍷", keywords: ["와인"] },
  { emoji: "🥤", keywords: ["음료"] },
  { emoji: "🌍", keywords: ["지구", "세계"] },
  { emoji: "🗺️", keywords: ["지도", "여행"] },
  { emoji: "⛰️", keywords: ["산"] },
  { emoji: "🌋", keywords: ["화산"] },
  { emoji: "🏕️", keywords: ["캠핑"] },
  { emoji: "🏖️", keywords: ["해변", "바다"] },
  { emoji: "🏝️", keywords: ["섬"] },
  { emoji: "🏠", keywords: ["집", "홈"] },
  { emoji: "🏢", keywords: ["회사", "건물"] },
  { emoji: "🏫", keywords: ["학교"] },
  { emoji: "🏰", keywords: ["성"] },
  { emoji: "⛪", keywords: ["교회"] },
  { emoji: "🗼", keywords: ["타워"] },
  { emoji: "🗽", keywords: ["자유의여신상"] },
  { emoji: "⛲", keywords: ["분수"] },
  { emoji: "⛺", keywords: ["텐트"] },
  { emoji: "🚗", keywords: ["차", "자동차"] },
  { emoji: "🚕", keywords: ["택시"] },
  { emoji: "🚌", keywords: ["버스"] },
  { emoji: "🚆", keywords: ["기차"] },
  { emoji: "🚇", keywords: ["지하철"] },
  { emoji: "✈️", keywords: ["여행", "비행기"] },
  { emoji: "🚀", keywords: ["로켓", "스타트업"] },
  { emoji: "🛸", keywords: ["우주선"] },
  { emoji: "🚁", keywords: ["헬기"] },
  { emoji: "⛵", keywords: ["배", "요트"] },
  { emoji: "⚓", keywords: ["닻"] },
  { emoji: "🚲", keywords: ["자전거"] },
  { emoji: "🛵", keywords: ["스쿠터"] },
  { emoji: "🚨", keywords: ["사이렌"] },
  { emoji: "⏰", keywords: ["시계", "알람"] },
  { emoji: "🌙", keywords: ["달", "밤"] },
  { emoji: "☀️", keywords: ["해", "날씨", "맑음"] },
  { emoji: "⭐", keywords: ["별", "즐겨찾기"] },
  { emoji: "🌟", keywords: ["반짝", "별"] },
  { emoji: "⚡", keywords: ["번개", "에너지"] },
  { emoji: "🔥", keywords: ["불", "핫", "인기"] },
  { emoji: "💧", keywords: ["물", "물방울"] },
  { emoji: "🌊", keywords: ["파도", "바다"] },
  { emoji: "🌈", keywords: ["무지개"] },
  { emoji: "❄️", keywords: ["눈", "겨울"] },
  { emoji: "☔", keywords: ["비", "우산"] },
  { emoji: "🎃", keywords: ["호박", "할로윈"] },
  { emoji: "🎄", keywords: ["크리스마스", "트리"] },
  { emoji: "🎉", keywords: ["축하", "파티"] },
  { emoji: "🎊", keywords: ["축하"] },
  { emoji: "🎁", keywords: ["선물"] },
  { emoji: "🎈", keywords: ["풍선"] },
  { emoji: "🏆", keywords: ["트로피", "우승"] },
  { emoji: "🥇", keywords: ["금메달", "1등"] },
  { emoji: "⚽", keywords: ["축구"] },
  { emoji: "🏀", keywords: ["농구"] },
  { emoji: "🏈", keywords: ["미식축구"] },
  { emoji: "⚾", keywords: ["야구"] },
  { emoji: "🎾", keywords: ["테니스"] },
  { emoji: "🏐", keywords: ["배구"] },
  { emoji: "🎱", keywords: ["당구"] },
  { emoji: "🏓", keywords: ["탁구"] },
  { emoji: "🎮", keywords: ["게임"] },
  { emoji: "🕹️", keywords: ["조이스틱", "게임"] },
  { emoji: "🎲", keywords: ["주사위", "보드게임"] },
  { emoji: "🧩", keywords: ["퍼즐"] },
  { emoji: "♟️", keywords: ["체스"] },
  { emoji: "🎯", keywords: ["목표", "타겟"] },
  { emoji: "🎸", keywords: ["기타", "음악"] },
  { emoji: "🎹", keywords: ["피아노"] },
  { emoji: "🥁", keywords: ["드럼"] },
  { emoji: "🎤", keywords: ["마이크", "노래"] },
  { emoji: "🎧", keywords: ["헤드폰", "음악"] },
  { emoji: "🎬", keywords: ["영화", "촬영"] },
  { emoji: "🎭", keywords: ["공연", "연극"] },
  { emoji: "🎨", keywords: ["팔레트", "디자인", "그림"] },
  { emoji: "🖼️", keywords: ["그림", "액자"] },
  { emoji: "📷", keywords: ["사진", "카메라"] },
  { emoji: "🎥", keywords: ["카메라", "영상"] },
  { emoji: "📱", keywords: ["폰", "스마트폰"] },
  { emoji: "💻", keywords: ["컴퓨터", "코딩", "작업", "노트북"] },
  { emoji: "⌨️", keywords: ["키보드"] },
  { emoji: "🖥️", keywords: ["모니터", "데스크톱"] },
  { emoji: "🖨️", keywords: ["프린터"] },
  { emoji: "🖱️", keywords: ["마우스"] },
  { emoji: "💾", keywords: ["저장"] },
  { emoji: "💿", keywords: ["시디"] },
  { emoji: "📀", keywords: ["디브이디"] },
  { emoji: "🔍", keywords: ["검색", "찾기"] },
  { emoji: "💡", keywords: ["아이디어", "전구"] },
  { emoji: "🔦", keywords: ["손전등"] },
  { emoji: "📖", keywords: ["책", "읽기"] },
  { emoji: "📚", keywords: ["책", "읽기", "공부"] },
  { emoji: "📝", keywords: ["메모", "노트"] },
  { emoji: "✏️", keywords: ["연필"] },
  { emoji: "📌", keywords: ["핀", "고정"] },
  { emoji: "📎", keywords: ["클립"] },
  { emoji: "📁", keywords: ["폴더", "파일"] },
  { emoji: "📂", keywords: ["폴더"] },
  { emoji: "📅", keywords: ["달력", "일정"] },
  { emoji: "📊", keywords: ["차트", "데이터", "그래프"] },
  { emoji: "📈", keywords: ["상승", "성장"] },
  { emoji: "📉", keywords: ["하락"] },
  { emoji: "📋", keywords: ["클립보드"] },
  { emoji: "📬", keywords: ["메일", "편지"] },
  { emoji: "📦", keywords: ["박스", "배송"] },
  { emoji: "💼", keywords: ["업무", "회사", "가방"] },
  { emoji: "👜", keywords: ["가방"] },
  { emoji: "🛒", keywords: ["쇼핑", "장바구니"] },
  { emoji: "🛍️", keywords: ["쇼핑백"] },
  { emoji: "💎", keywords: ["다이아", "보석"] },
  { emoji: "💰", keywords: ["돈", "돈주머니"] },
  { emoji: "💸", keywords: ["지출"] },
  { emoji: "💳", keywords: ["카드"] },
  { emoji: "🔑", keywords: ["열쇠", "키"] },
  { emoji: "🔒", keywords: ["잠금", "보안"] },
  { emoji: "🧲", keywords: ["자석"] },
  { emoji: "⚙️", keywords: ["설정", "톱니"] },
  { emoji: "🔧", keywords: ["공구", "수리"] },
  { emoji: "🔨", keywords: ["망치"] },
  { emoji: "🧰", keywords: ["툴박스", "도구"] },
  { emoji: "🧪", keywords: ["실험", "과학"] },
  { emoji: "🧬", keywords: ["dna", "유전자"] },
  { emoji: "🔭", keywords: ["망원경"] },
  { emoji: "🔬", keywords: ["현미경"] },
  { emoji: "💊", keywords: ["약"] },
  { emoji: "🩺", keywords: ["병원", "건강"] },
  { emoji: "🧸", keywords: ["인형"] },
  { emoji: "🧹", keywords: ["청소"] },
  { emoji: "🧺", keywords: ["바구니"] },
  { emoji: "🧻", keywords: ["휴지"] },
  { emoji: "🫧", keywords: ["거품"] },
  { emoji: "❤️", keywords: ["하트", "좋아요", "사랑"] },
  { emoji: "🧡", keywords: ["주황하트"] },
  { emoji: "💛", keywords: ["노랑하트"] },
  { emoji: "💚", keywords: ["초록하트"] },
  { emoji: "💙", keywords: ["파랑하트"] },
  { emoji: "💜", keywords: ["보라", "하트"] },
  { emoji: "🖤", keywords: ["검은하트"] },
  { emoji: "🤍", keywords: ["흰하트"] },
  { emoji: "💔", keywords: ["상심"] },
  { emoji: "💕", keywords: ["하트"] },
  { emoji: "💞", keywords: ["하트"] },
  { emoji: "💯", keywords: ["백점", "완벽"] },
  { emoji: "✅", keywords: ["완료", "체크"] },
  { emoji: "❌", keywords: ["엑스", "취소"] },
  { emoji: "❓", keywords: ["질문"] },
  { emoji: "❗", keywords: ["중요"] },
  { emoji: "💬", keywords: ["말풍선", "채팅"] },
  { emoji: "💭", keywords: ["생각"] },
  { emoji: "🔔", keywords: ["알림", "종"] },
  { emoji: "🔖", keywords: ["북마크", "태그"] },
  { emoji: "🔗", keywords: ["링크"] },
  { emoji: "➡️", keywords: ["화살표"] },
  { emoji: "🔙", keywords: ["뒤로"] },
  { emoji: "🔝", keywords: ["위"] },
  { emoji: "🎵", keywords: ["음표", "음악"] },
  { emoji: "🎶", keywords: ["노래"] },
  { emoji: "♻️", keywords: ["재활용"] },
  { emoji: "⚠️", keywords: ["주의"] },
  { emoji: "🚫", keywords: ["금지"] },
  { emoji: "🌀", keywords: ["소용돌이"] },
  { emoji: "✨", keywords: ["반짝", "추천"] },
  { emoji: "🪐", keywords: ["행성", "우주"] },
  { emoji: "☁️", keywords: ["구름"] },
  { emoji: "🌤️", keywords: ["날씨"] },
];

const FREQUENT = ["📁", "⭐", "❤️", "📌", "✨", "💡", "🔗", "📚", "🎧", "💻"];

export function searchEmojis(query: string) {
  const keyword = query.trim().toLowerCase();
  if (!keyword) {
    return FREQUENT.map((emoji) => EMOJI_LIBRARY.find((item) => item.emoji === emoji) ?? { emoji, keywords: [] });
  }
  return EMOJI_LIBRARY.filter(
    (item) => item.emoji.includes(keyword) || item.keywords.some((word) => word.includes(keyword) || keyword.includes(word))
  );
}

export function recommendEmojis(folderName: string) {
  const text = folderName.trim().toLowerCase();
  if (!text) return searchEmojis("");
  const scored = EMOJI_LIBRARY.filter((item) => item.keywords.some((word) => text.includes(word)));
  if (scored.length > 0) return scored;
  return searchEmojis("");
}

export function takeEmojiInput(text: string) {
  const trimmed = text.trim();
  if (!trimmed) return null;
  try {
    const segmenter = new Intl.Segmenter(undefined, { granularity: "grapheme" });
    const first = [...segmenter.segment(trimmed)][0]?.segment;
    if (first && /\p{Extended_Pictographic}/u.test(first)) return first;
  } catch {
    const match = trimmed.match(/\p{Extended_Pictographic}/u);
    if (match) return match[0];
  }
  return null;
}
